services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '9080:3000'
    env_file:
      - .env.sample
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}
