---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Homelab System Monitoring:
    style: row
    columns: 1 # Full-width section for the top Glances widget
  NAS Overview:
    style: row
    columns: 3 # 3x2 grid for the other Glances widgets
